name: PR

on:
  pull_request:
    branches:
      - main

env:
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings

jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Cargo cache
        uses: actions/cache@v2
        with:
          key: ${{ github.sha }}
          path: |
            ~/.cargo/bin
            ~/.cargo/git/db
            ~/.cargo/registry/cache
            ~/.cargo/registry/index
            Cargo.lock
      - name: Update
        run: cargo update

  check:
    runs-on: ubuntu-20.04
    needs: [update]
    strategy:
      matrix:
        aws-sdk: [true, false]
    steps:
      - uses: actions/checkout@v2
      - name: Cargo cache
        uses: actions/cache@v2
        with:
          key: ${{ github.sha }}
          path: |
            ~/.cargo/bin
            ~/.cargo/git/db
            ~/.cargo/registry/cache
            ~/.cargo/registry/index
            Cargo.lock
      - name: Check cache
        uses: actions/cache@v2
        with:
          key: check-${{ matrix.aws-sdk }}-${{ hashFiles('Cargo.lock') }}
          path: target
      - name: Check
        run: |
          cargo check --all-targets --no-default-features \
            --features rustls \
            ${{ matrix.aws-sdk && '--features aws-sdk' || '' }}

  clippy:
    runs-on: ubuntu-20.04
    needs: [check]
    strategy:
      matrix:
        aws-sdk: [true, false]
    steps:
      - uses: actions/checkout@v2
      - name: Cargo cache
        uses: actions/cache@v2
        with:
          key: ${{ github.sha }}
          path: |
            ~/.cargo/bin
            ~/.cargo/git/db
            ~/.cargo/registry/cache
            ~/.cargo/registry/index
            Cargo.lock
      - name: Check cache
        uses: actions/cache@v2
        with:
          key: check-${{ matrix.aws-sdk }}-${{ hashFiles('Cargo.lock') }}
          path: target
      - name: Clippy
        run: |
          cargo clippy --all-targets --no-default-features \
            --features rustls \
            ${{ matrix.aws-sdk && '--features aws-sdk' || '' }}

  doc-check:
    runs-on: ubuntu-20.04
    needs: [check]
    strategy:
      matrix:
        aws-sdk: [true, false]
    steps:
      - uses: actions/checkout@v2
      - name: Cargo cache
        uses: actions/cache@v2
        with:
          key: ${{ github.sha }}
          path: |
            ~/.cargo/bin
            ~/.cargo/git/db
            ~/.cargo/registry/cache
            ~/.cargo/registry/index
            Cargo.lock
      - name: Check cache
        uses: actions/cache@v2
        with:
          key: check-${{ matrix.aws-sdk }}-${{ hashFiles('Cargo.lock') }}
          path: target
      - name: Doc check
        run: |
          cargo doc --no-deps --no-default-features \
            --features rustls \
            ${{ matrix.aws-sdk && '--features aws-sdk' || '' }}

  test:
    runs-on: ubuntu-20.04
    needs: [update]
    strategy:
      matrix:
        aws-sdk: [true, false]
    steps:
      - uses: actions/checkout@v2
      - name: Cargo cache
        uses: actions/cache@v2
        with:
          key: ${{ github.sha }}
          path: |
            ~/.cargo/bin
            ~/.cargo/git/db
            ~/.cargo/registry/cache
            ~/.cargo/registry/index
            Cargo.lock
      - name: Test cache
        uses: actions/cache@v2
        with:
          key: test-${{ matrix.aws-sdk }}-${{ hashFiles('Cargo.lock') }}
          path: target
      - name: Test
        run: |
          cargo test --no-default-features \
            --features rustls \
            ${{ matrix.aws-sdk && '--features aws-sdk' || '' }}

  status:
    runs-on: ubuntu-20.04
    needs: [clippy, doc-check, test]
    if: always()
    steps:
      - run: exit 1
        if: needs.clippy.result != 'success' || needs.doc-check.result != 'success' || needs.test.result != 'success'
